### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by DavidMStraub** [apik/mr#8]
Hi,

I'm trying to build the program according to the instructions. I cloned the repo and configured with
```
autoreconf -i
./configure --with-mcc-path=/usr/local/bin/mcc --enable-math10
```

Running `make` fails with the following error:

```
mr.tm -o mr.cpp
/bin/bash: mr.tm: Command not found
```

I am using Linux 4.13 on Ubuntu 17.10 with gcc 7.2.0 and Mathematica 11.

**Comment by apik** [comment]
Dear David,

Configure script option `--with-mcc-path` should point to the path, where `mprep` command is located, please change it accordingly.

For example, on my Linux machine I use the following configuration option:

`--with-mcc-path=/opt/mathematica/10.0/SystemFiles/Links/MathLink/DeveloperKit/Linux-x86-64/CompilerAdditions`

**Comment by DavidMStraub** [comment]
Oh sorry, that was indeed the problem. After installing in addition the `uuid-dev` Ubuntu package (similarly to #7) it now works like a charm. Thanks!
